import React, { useContext, useState } from "react";
import Head from "next/head";
import NoLogin from "../../components/NoLogin";
import { useCookies } from "react-cookie";
import { useEffect } from "react";
import { Context } from "../../context/state";

import Link from "next/link"
function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}

export default function Admin() {
  const [cookies, setCookies] = useCookies(["CIS_1"]);
  const { getPosts, changeEstate, rootState } = useContext(Context);

  const changeState = async (event) => {

    console.log()
    let someInfo = {
      name: event.target.getAttribute('name'),
      id: event.target.id
    }
    await changeEstate(someInfo);
  };
   
  const getTables = async (event) => {
    await getPosts();
  };

  if (rootState.lomakkeet.length === 0) {
    console.log("imnothere");
    getTables();
  }


  if (cookies.CIS_1) {
    return (
      <>
        <Head>
          <title>Esedu_Lanit | Käyttäjäpaneeli </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="md:ml-32 md:mr-32">
          <div className="mt-20 mb-20 relative overflow-x-auto shadow-md sm:rounded-lg">

            <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400">
              <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                  <th scope="col" className="p-4">
                    <div className="flex items-center">
                      <input
                        id="checkbox-all-search"
                        type="checkbox"
                        className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                      />
                      <label htmlFor="checkbox-all-search" className="sr-only">
                        checkbox
                      </label>
                    </div>
                  </th>
                  <th scope="col" className="px-6 py-3">
                    Etu- ja Sukunimi
                  </th>
                  <th scope="col" className="px-6 py-3">
                    Puhelinnumero
                  </th>
                  <th scope="col" className="px-6 py-3">
                    Discord ID
                  </th>
                  <th scope="col" className="px-6 py-3">
                    Tila
                  </th>
                  <th scope="col" className="px-6 py-3">
                    <span className="sr-only">Edit</span>
                  </th>
                </tr>
              </thead>
              <tbody>

              {rootState.lomakkeet !== "" ? (<>
                {rootState.lomakkeet.map((item, index) => {
                  return (
                    <tr
                      key={index}
                      className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
                    >
                      <td className="w-4 p-4">
                        <div className="flex items-center">
                          <input
                            id="checkbox-table-search-1"
                            type="checkbox"
                            className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                          />
                          <label
                            htmlFor="checkbox-table-search-1"
                            className="sr-only"
                          >
                            checkbox
                          </label>
                        </div>
                      </td>
                      <th
                        scope="row"
                        className="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap"
                      >
                        {item.Etunimi} {item.Sukunimi}
                      </th>
                      <td className="px-6 py-4">{item.Puhelin}</td>
                      <td className="px-6 py-4">{item.DiscordID}</td>
                      <td className="px-6 py-4">
                        {item.tila ===  "0" ? (
                          <span className="text-yellow-400"> Odottaa</span>
                        ) : (
                          <>
                            {item.tila === "1" ? (
                              <span className="text-green-400">Hyväksytty</span>
                            ) : (
                              <>
                                {item.tila ===  "2" ? (
                                  <span className="text-yellow-100">
                                    Jonossa
                                  </span>
                                ) : (
                                  <>
                                    {item.tila === "3" ? (
                                     <span className="text-red-400">
                                        Hylätty
                                      </span> 
                                    ) : (
                                      <>
                                      
                                      {item.tila ===  "4" ? (
                                     <span className="text-blue-400">
                                        Töissä
                                      </span> 
                                    ) : (
                                      <>
                                      
                                      
                                      <span className="text-red-900">
                                        Tuntematon
                                      </span> 
                                      </>
                                    )}
                                      
                                      </>
                                    )}
                                  </>
                                )}
                              </>
                            )}
                          </>
                        )}
                      </td>
                      <td className="px-6 py-4 text-right">
                        <div className="dropdown">
                          <button className="dropbtn font-medium text-blue-600 dark:text-blue-500 hover:underline">Muuta</button>
                          <div className="dropdown-content">
                           
                           < span className="cursor-pointer" name="1" id={item.id} onClick={changeState}>Hyväksy</span>
                           < span className="cursor-pointer" name="2" id={item.id} onClick={changeState}>Jonoon</span>
                           < span className="cursor-pointer" name="3" id={item.id} onClick={changeState}>Hylätty</span>
                           < span className="cursor-pointer" name="4" id={item.id} onClick={changeState}>Töissä</span>
                            < span   className="cursor-pointer" name="0" id={item.id} onClick={changeState}>Odota</span>
                          </div>
                        </div>

                        {/* <a
                          id={item.id}
                          onClick={openThis}
                          href="#"
                          className="font-medium text-blue-600 dark:text-blue-500 hover:underline"
                        
                        >
                          Hyväksy
                        </a> */}
                      </td>
                    </tr>
                  );
                })}
               </> ) : null}
              </tbody>
            </table>
          </div>
       
        </div>
      </>
    );
  } else {
    return (
      <>
        <NoLogin />
      </>
    );
  }
}
