import Head from "next/head";
import Ilmoittautuminen from "../components/Ilmoittautuminen";

export default function Home() {
  return (
    <>
      <Head>
        <title>Esedu_Lanit | Ilmoittautuminen </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="md:ml-32 md:mr-32">
        <Ilmoittautuminen />

        <div className="md:ml-32 md:mr-32"> </div>
      </div>
    </>
  );
}
