import Head from 'next/head'


export default function PrivacyPolicy() {
  return (
    <>
      <Head>
      <title>Esedu_Lanit | Privacy-Policy </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className='md:ml-32 md:mr-32'>
        <h1 className="text-3xl mt-20 ">
        Privacy-Policy
        </h1>





        <div className='md:ml-32 md:mr-32'> </div>



      </div>

    </>
  )
}
